services:
  mariadb:
    image: mariadb:11.8
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - TZ=${TZ:-UTC}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-}
      - MARIADB_RANDOM_ROOT_PASSWORD=${MARIADB_RANDOM_ROOT_PASSWORD:-}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-aio}
      - MARIADB_USER=${MARIADB_USER:-${MARIADB_DATABASE:-aio}}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-}

    volumes:
      - db:/var/lib/mysql

    networks:
      default:
        ipv4_address: 169.254.4.2
        aliases:
          - db

  redis:
    image: redis:alpine
    restart: always
    networks:
      default:
        ipv4_address: 169.254.4.3

volumes:
  db:

networks:
  default:
    internal: true
    driver: bridge
    name: internal
    ipam:
      driver: default
      config:
        - subnet: 169.254.4.0/24
          ip_range: 169.254.4.0/24
